### PR TITLE
Deploy Optic to Google Cloud Platform

### PR DESCRIPTION
**Pull request by Eomm**
Opening as draft PR to run the CD action manually to check out the behaviour

### CODE REVIEW

**Comment by simoneb** [comment]
Thanks, it all makes sense. The notifications works here, so the setup seems correct. This PR is ready for review.

**Comment by simoneb** [comment]
This failed deployment is fixed by these changes? https://github.com/nearform/optic/runs/3823792642

**Comment by Eomm** [comment]
> This failed deployment is fixed by these changes? https://github.com/nearform/optic/runs/3823792642

Yes, it is covered by the documentation. See `Configure the default Cloud Build Service Account`

> the env parameter are provided during build time and run time

The env vars are needed at runtime:
https://github.com/nearform/optic/blob/fcfd0934b31478e8642640e653365622adbb8821/src/Main.js#L32

> the timeout

It could be an issue, monitoring here https://github.com/google-github-actions/deploy-cloudrun/issues/239

**Comment by simoneb** [comment]
don't forget to merge this PR if you're happy with it

**Pull request merged**
